Update QStash Python SDK docs
upstash/docs pull request #194
Opened 2024-06-12 11:56 UTC by mdumandag

We have rewritten the SDK, so this PR updates the places where we gave SDK code snippets for it.

It should be merged after we release the new version of the SDK.

2024-06-14 12:47 UTC, CahidArda commented
should rename this file as well I think https://github.com/upstash/docs/blob/0b17486fb0cc4b882d8a6c51195f46f92a5eae15/qstash/features/topics.mdx

2024-06-14 13:37 UTC, mdumandag commented
Let's leave that to a later, when we update the UI etc. I intentionally didn't change any other part than the Python related parts where we renamed topic to url group.

2024-06-26 15:59 UTC, CahidArda commented
> Let's leave that to a later, when we update the UI etc. I intentionally didn't change any other part than the Python related parts where we renamed topic to url group.

we updated the console btw, qstash-js is also updated.

we should update docs/examples to use url group instead of topic. I will update them

2024-07-16 15:28 UTC, CahidArda commented
I have completed the changes in Qstash and Qstash JS.

there are already too many changes in this PR, I feel like we can go ahead with this PR and complete rest of the topic -> URL group changes in another PR.

2024-07-16 15:47 UTC, CahidArda requested changes
can we add examples for queues in

2024-07-16 15:47 UTC, CahidArda commented on oss/sdks/py/qstash/examples/url-groups.mdx
> +---
can we create py/qstash/examples/queues.mdx file and examples for queues?

2024-07-18 16:41 UTC, CahidArda approved these changes

2024-07-19 06:35 UTC, merged