QStash Ratelimit Response Headers
upstash/docs pull request #271
Opened 2024-09-20 12:31 UTC by fahreddinozcan

2024-09-20 13:53 UTC, CahidArda commented on qstash/api/api-ratelimiting.mdx
> +try {
we can show how to import these custom errors

2024-09-23 06:27 UTC, CahidArda approved these changes

2024-09-23 06:43 UTC, mehmettokgoz requested changes

2024-09-23 06:43 UTC, mehmettokgoz commented on qstash/api/api-ratelimiting.mdx
> +This is a **daily** limit applied across all API endpoints.
The daily rate limit refers to the maximum number of messages that can be published per day. It is consumed by new message requests like publish, enqueue, or batch. Other API requests, such as fetching events or messages, do not count toward this limit.

2024-09-23 06:43 UTC, mehmettokgoz commented on qstash/api/api-ratelimiting.mdx
> +  }
Maybe we should put different API request for each error type? Because `client.events()` never throws `QstashChatRatelimitError`.

2024-09-23 06:43 UTC, mehmettokgoz commented on qstash/api/api-ratelimiting.mdx
> +- `x-ratelimit-remaining-tokens`: Remaining number of tokens
Time period for these values are missing (like `1 day`)

2024-09-23 06:43 UTC, mehmettokgoz commented on qstash/api/api-ratelimiting.mdx
> +This is a short-term limit **per second** to prevent rapid bursts of requests.
Since the daily limit applies only to publish-related requests, we can emphasize that the burst limit applies to **_all_** API endpoints.

2024-09-27 08:12 UTC, mehmettokgoz approved these changes

2024-09-27 08:15 UTC, merged